
import React, { useState } from 'react';
import { StudentData, PsychometricScore } from '../types';
import { 
  Brain, ChevronRight, ChevronLeft, Sparkles, Zap, Target, Clock, ShieldAlert,
  Loader2, HeartHandshake, Moon, Activity, UserCheck, Users, Layout, Trophy,
  AlertTriangle, Lightbulb, CheckCircle2, Fingerprint, Eye, Coffee, Thermometer,
  Compass, BarChart, History, Flame, Timer, Gauge, ShieldCheck
} from 'lucide-react';
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ResponsiveContainer } from 'recharts';

interface PsychometricTestProps {
  data: StudentData;
  setData: (data: StudentData) => void;
}

const PsychometricTest: React.FC<PsychometricTestProps> = ({ data, setData }) => {
  const [step, setStep] = useState(0);
  const [isFinishing, setIsFinishing] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<any>(null);

  const [scores, setScores] = useState<Record<string, number>>({
    sillyMistakes: 5,
    focusStamina: 5,
    backlogStress: 5,
    sleepSync: 5,
    conceptEncoding: 5,
    examStoicism: 5,
    numericalPhobia: 5,
    socialIsolation: 5,
    routineDiscipline: 5,
    recoverySpeed: 5,
    competitivePressure: 5,
    revisionConsistency: 5
  });

  const questions = [
    { id: 'sillyMistakes', title: 'Precision Drift', subtitle: 'Frequency of "silly errors" despite knowing the concept fully.', low: 'Laser Accurate', high: 'Erratic', icon: Target, color: 'emerald' },
    { id: 'focusStamina', title: 'Deep Work Capacity', subtitle: 'Ability to stay in a single numerical problem for 15+ minutes without distraction.', low: 'Low Stamina', high: 'Unbreakable', icon: Timer, color: 'indigo' },
    { id: 'numericalPhobia', title: 'Calculative Friction', subtitle: 'Resistance or "fear" when facing heavy multi-step calculations.', low: 'Stoic', high: 'Aversion', icon: Gauge, color: 'rose' },
    { id: 'conceptEncoding', title: 'Encoding Velocity', subtitle: 'Speed of grasping new complex theoretical derivations.', low: 'Foggy', high: 'Acute', icon: Fingerprint, color: 'blue' },
    { id: 'examStoicism', title: 'Test Performance Stoicism', subtitle: 'Maintaining calm when facing 3-4 consecutive unsolved questions.', low: 'Panic Prone', high: 'Battle Hardened', icon: ShieldAlert, color: 'violet' },
    { id: 'backlogStress', title: 'Cumulative Debt Anxiety', subtitle: 'Mental noise generated by the thought of unfinished units.', low: 'Zero Weight', high: 'Paralyzing', icon: Activity, color: 'amber' },
    { id: 'sleepSync', title: 'Circadian Alignment', subtitle: 'Restorative quality of sleep and alertness during morning hours.', low: 'Desynced', high: 'Optimized', icon: Moon, color: 'blue' },
    { id: 'recoverySpeed', title: 'Burnout Recovery', subtitle: 'How quickly you bounce back after a bad mock test result.', low: 'Slow/Lingering', high: 'Instant Reset', icon: Flame, color: 'orange' },
    { id: 'routineDiscipline', title: 'Schedule Adherence', subtitle: 'Strictness in following the planned time-table vs impulsive studying.', low: 'Impulsive', high: 'Clockwork', icon: CheckCircle2, color: 'emerald' },
    { id: 'socialIsolation', title: 'Synergy vs Solitude', subtitle: 'Feeling healthy solitude vs feeling disconnected/lonely.', low: 'Healthy', high: 'Isolated', icon: Users, color: 'teal' },
    { id: 'competitivePressure', title: 'Relative Comparison', subtitle: 'Mental load from comparing your rank with peers or toppers.', low: 'Self-Focused', high: 'Peer-Obsessed', icon: Compass, color: 'indigo' },
    { id: 'revisionConsistency', title: 'Memory Maintenance', subtitle: 'Discipline in revisiting "Easy" topics to prevent decay.', low: 'Negligent', high: 'Rigorous', icon: History, color: 'rose' }
  ];

  const radarData = questions.slice(0, 6).map(q => ({
    subject: q.title,
    A: scores[q.id] * 10,
    fullMark: 100
  }));

  const handleFinish = async () => {
    setIsFinishing(true);
    await new Promise(r => setTimeout(r, 2000));

    const fatigueIndex = (scores.sillyMistakes + (10 - scores.sleepSync) + (10 - scores.recoverySpeed)) / 3;
    const executionStrength = (scores.focusStamina + scores.routineDiscipline + scores.revisionConsistency) / 3;
    const anxietyLoad = (scores.examStoicism + scores.numericalPhobia + scores.backlogStress) / 3;
    
    let archetype = "The Steady Aspirant";
    let riskLevel = "LOW";
    let statusBg = "bg-emerald-600";
    
    if (fatigueIndex > 7) { 
        archetype = "The Redline Performer"; riskLevel = "CRITICAL"; statusBg = "bg-rose-600";
    } else if (anxietyLoad > 7) { 
        archetype = "The Perfectionist Miner"; riskLevel = "ELEVATED"; statusBg = "bg-amber-600";
    } else if (executionStrength > 7) { 
        archetype = "The Strategic Machine"; riskLevel = "OPTIMAL"; statusBg = "bg-indigo-600";
    }

    const report = {
      archetype, riskLevel, statusBg,
      indices: {
        focus: Math.round(executionStrength * 10),
        resilience: Math.round((10 - anxietyLoad) * 10),
        vitality: Math.round((10 - fatigueIndex) * 10)
      },
      summaryText: `Your current cognitive state is identified as '${archetype}'. ${fatigueIndex > 6 ? 'Significant neural fatigue detected.' : 'Healthy load management observed.'}`
    };

    setAiAnalysis(report);
    
    const newEntry: PsychometricScore = {
      stress: Math.round(anxietyLoad),
      focus: Math.round(executionStrength),
      motivation: Math.round(scores.recoverySpeed),
      examFear: Math.round(scores.examStoicism),
      timestamp: new Date().toISOString().split('T')[0],
      studentSummary: report.summaryText,
      parentAdvice: fatigueIndex > 6 ? "High risk of burnout. Mandatory rest suggested." : "Stable performance. Reinforce consistency."
    };

    setData({ ...data, psychometricHistory: [...(data.psychometricHistory || []), newEntry] });
    setIsFinishing(false);
    setStep(questions.length);
  };

  const currentQ = questions[step];

  if (step === questions.length) {
    return (
      <div className="max-w-6xl mx-auto space-y-8 animate-in zoom-in-95 duration-700 pb-32 px-4">
        {aiAnalysis && (
          <div className="bg-white rounded-[4rem] border border-slate-200 shadow-2xl overflow-hidden">
             <div className={`p-12 text-white relative overflow-hidden ${aiAnalysis.statusBg}`}>
                <div className="absolute top-0 right-0 p-12 opacity-10 rotate-12"><Brain className="w-64 h-64" /></div>
                <div className="relative z-10 space-y-6">
                   <div className="inline-flex px-4 py-1.5 rounded-full bg-white/20 backdrop-blur-md text-[10px] font-black uppercase tracking-widest border border-white/20">Result: {aiAnalysis.riskLevel} Risk</div>
                   <h2 className="text-6xl font-black italic tracking-tighter uppercase leading-none">{aiAnalysis.archetype}.</h2>
                   <p className="text-white/80 max-w-2xl text-lg font-medium leading-relaxed italic">"{aiAnalysis.summaryText}"</p>
                </div>
             </div>
             <div className="p-12 grid grid-cols-1 lg:grid-cols-3 gap-12">
                <div className="space-y-8">
                   <h4 className="text-[10px] font-black uppercase text-slate-400 tracking-[0.3em] flex items-center gap-2"><Activity className="w-4 h-4" /> Performance Indices</h4>
                   {Object.entries(aiAnalysis.indices).map(([k, v]: any) => (
                     <div key={k} className="space-y-2">
                        <div className="flex justify-between text-xs font-black uppercase text-slate-700">{k} <span className="text-slate-900">{v}%</span></div>
                        <div className="w-full h-3 bg-slate-100 rounded-full overflow-hidden"><div className="h-full bg-indigo-500" style={{ width: `${v}%` }}></div></div>
                     </div>
                   ))}
                </div>
                <div className="lg:col-span-2 flex flex-col items-center justify-center p-10 bg-slate-50 rounded-[3rem] border border-slate-100">
                   <div className="h-64 w-64">
                      <ResponsiveContainer width="100%" height="100%">
                         <RadarChart cx="50%" cy="50%" outerRadius="80%" data={radarData}>
                            <PolarGrid stroke="#e2e8f0" />
                            <PolarAngleAxis dataKey="subject" tick={false} />
                            <Radar name="Student" dataKey="A" stroke="#6366f1" fill="#6366f1" fillOpacity={0.4} />
                         </RadarChart>
                      </ResponsiveContainer>
                   </div>
                   <p className="text-[10px] font-black uppercase text-slate-400 mt-4 tracking-widest">Cognitive Equilibrium Map</p>
                </div>
             </div>
             <div className="p-12 border-t border-slate-100 text-center">
                <button onClick={() => setStep(0)} className="px-12 py-5 bg-slate-900 text-white rounded-[2rem] font-black text-[10px] uppercase tracking-[0.3em] hover:scale-105 transition-all shadow-xl">Re-Sync Intelligence</button>
             </div>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-12 animate-in fade-in duration-500 pb-32 px-4 text-center">
      <div className="space-y-4">
         <div className="inline-flex items-center gap-3 px-6 py-2 bg-indigo-50 border border-indigo-100 rounded-full text-[10px] font-black uppercase tracking-[0.4em] text-indigo-600 mx-auto">
            <Compass className="w-4 h-4" /> Dimension {step + 1} of {questions.length}
         </div>
         <h2 className="text-6xl font-black text-slate-900 tracking-tighter italic uppercase">Pulse Check.</h2>
      </div>

      <div className="bg-white p-12 lg:p-20 rounded-[4rem] border border-slate-200 shadow-2xl space-y-12 relative overflow-hidden group text-left">
        <div className="absolute top-0 right-0 p-12 opacity-[0.03] group-hover:opacity-[0.08] transition-opacity"><Brain className="w-96 h-96" /></div>
        <div className="flex flex-col items-center text-center space-y-10 relative z-10">
          <div className={`w-28 h-28 bg-${currentQ.color}-50 text-${currentQ.color}-600 rounded-[3rem] flex items-center justify-center shadow-inner border border-${currentQ.color}-100`}>
            <currentQ.icon className="w-14 h-14" />
          </div>
          <div className="space-y-4">
            <h3 className="text-5xl font-black text-slate-900 tracking-tighter italic uppercase">{currentQ.title}</h3>
            <p className="text-slate-500 text-xl font-medium max-w-2xl leading-relaxed italic">"{currentQ.subtitle}"</p>
          </div>
          <div className="w-full max-w-2xl pt-12 space-y-12">
            <input 
              type="range" min="1" max="10" step="1"
              value={scores[currentQ.id]}
              onChange={(e) => setScores({...scores, [currentQ.id]: parseInt(e.target.value)})}
              className="w-full h-4 bg-slate-100 rounded-full appearance-none cursor-pointer accent-indigo-600 outline-none shadow-inner"
            />
            <div className="flex justify-between mt-6">
               <div className="text-left space-y-1"><div className="text-[9px] font-black text-slate-300 uppercase tracking-widest">Min</div><div className="text-xs font-black text-slate-400 uppercase">{currentQ.low}</div></div>
               <div className="text-7xl font-black text-indigo-600 tracking-tighter tabular-nums leading-none">{scores[currentQ.id]}</div>
               <div className="text-right space-y-1"><div className="text-[9px] font-black text-slate-300 uppercase tracking-widest">Max</div><div className="text-xs font-black text-slate-400 uppercase">{currentQ.high}</div></div>
            </div>
            <div className="flex justify-between items-center gap-8 pt-12">
              <button disabled={step === 0} onClick={() => setStep(step - 1)} className="flex-1 py-6 bg-slate-50 text-slate-400 font-black rounded-3xl transition-all uppercase text-[10px] tracking-widest disabled:opacity-20 border border-slate-100">Previous</button>
              <button onClick={() => step === questions.length - 1 ? handleFinish() : setStep(step + 1)} disabled={isFinishing} className="flex-[2] bg-indigo-600 text-white py-6 rounded-[2.5rem] font-black text-xs uppercase tracking-[0.3em] shadow-2xl flex items-center justify-center gap-4 hover:scale-105 transition-all">
                {isFinishing ? <Loader2 className="w-5 h-5 animate-spin" /> : step === questions.length - 1 ? <><Sparkles className="w-5 h-5" /> Finalize Diagnostic</> : <>Next Protocol <ChevronRight className="w-4 h-4" /></>}
              </button>
            </div>
          </div>
        </div>
      </div>
      
      <div className="bg-indigo-50 p-10 rounded-[3rem] border border-indigo-100 flex items-center gap-8 shadow-sm">
         <div className="w-14 h-14 bg-white rounded-2xl flex items-center justify-center text-indigo-600 shadow-sm border border-indigo-100 shrink-0"><ShieldCheck className="w-8 h-8" /></div>
         <p className="text-xs text-indigo-800 font-bold leading-relaxed italic text-left">"Encryption established. Your mental state data is prioritized for 'Coach Advice' calibration in the v10.0 core."</p>
      </div>
    </div>
  );
};

export default PsychometricTest;
