
import React, { useState } from 'react';
import { StudentData, PsychometricScore } from '../types';
import { api } from '../services/apiService';
import { 
  Brain, ChevronRight, ChevronLeft, Sparkles, Zap, Target, Clock, ShieldAlert,
  Loader2, HeartHandshake, Moon, Activity, UserCheck, Users, Layout, Trophy,
  AlertTriangle, Lightbulb, CheckCircle2, Fingerprint, Eye, Coffee, Thermometer,
  Compass, BarChart, History, Flame, Timer, Gauge, ShieldCheck, RefreshCcw
} from 'lucide-react';
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, Radar as RadarArea, ResponsiveContainer } from 'recharts';

interface PsychometricTestProps {
  data: StudentData;
  setData: (data: StudentData) => void;
}

const PsychometricTest: React.FC<PsychometricTestProps> = ({ data, setData }) => {
  const [step, setStep] = useState(0);
  const [isFinishing, setIsFinishing] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<any>(null);

  const [scores, setScores] = useState<Record<string, number>>({
    sillyMistakes: 5,
    focusStamina: 5,
    backlogStress: 5,
    sleepSync: 5,
    conceptEncoding: 5,
    examStoicism: 5,
    numericalPhobia: 5,
    socialIsolation: 5,
    routineDiscipline: 5,
    recoverySpeed: 5,
    competitivePressure: 5,
    revisionConsistency: 5
  });

  const questions = [
    { id: 'sillyMistakes', title: 'Precision Drift', subtitle: 'Frequency of "silly errors" despite knowing the concept fully.', low: 'Laser Accurate', high: 'Erratic', icon: Target },
    { id: 'focusStamina', title: 'Deep Work Capacity', subtitle: 'Ability to stay in a single numerical problem for 15+ minutes without distraction.', low: 'Low Stamina', high: 'Unbreakable', icon: Timer },
    { id: 'numericalPhobia', title: 'Calculative Friction', subtitle: 'Resistance or "fear" when facing heavy multi-step calculations.', low: 'Stoic', high: 'Aversion', icon: Gauge },
    { id: 'conceptEncoding', title: 'Encoding Velocity', subtitle: 'Speed of grasping new complex theoretical derivations.', low: 'Foggy', high: 'Acute', icon: Fingerprint },
    { id: 'examStoicism', title: 'Stress Stoicism', subtitle: 'Maintaining calm when facing consecutive unsolved questions.', low: 'Panic Prone', high: 'Battle Hardened', icon: ShieldAlert },
    { id: 'backlogStress', title: 'Debt Anxiety', subtitle: 'Mental noise generated by the thought of unfinished units.', low: 'Zero Weight', high: 'Paralyzing', icon: Activity },
    { id: 'sleepSync', title: 'Circadian Alignment', subtitle: 'Restorative quality of sleep and alertness during morning hours.', low: 'Desynced', high: 'Optimized', icon: Moon },
    { id: 'recoverySpeed', title: 'Reset Velocity', subtitle: 'How quickly you bounce back after a bad mock test result.', low: 'Lingering', high: 'Instant Reset', icon: Flame }
  ];

  const handleFinish = async () => {
    setIsFinishing(true);
    await new Promise(r => setTimeout(r, 2000));

    const fatigueIndex = (scores.sillyMistakes + (10 - scores.sleepSync) + (10 - scores.recoverySpeed)) / 3;
    const executionStrength = (scores.focusStamina + scores.routineDiscipline + scores.revisionConsistency) / 3;
    const anxietyLoad = (scores.examStoicism + scores.numericalPhobia + scores.backlogStress) / 3;
    const highFear = scores.examStoicism > 7;
    
    let archetype = "The Steady Aspirant";
    let statusBg = "bg-indigo-600";
    let protocol = "The Flow-State Marathon";
    let protocolDesc = "Performance metrics are optimal. Maintain current routine but increase problem-solving difficulty by 15% to test stress limits.";

    if (fatigueIndex > 7) { 
        archetype = "The Redline Performer"; 
        statusBg = "bg-rose-600";
        protocol = "The Decompression Cycle";
        protocolDesc = "Your stress indices are redlining. Switch to 20-minute 'Focus Bursts' followed by 10-minute active recovery. Reduce screen time after 9 PM.";
    } else if (executionStrength < 6) { 
        archetype = "The Divergent Mind"; 
        statusBg = "bg-amber-600";
        protocol = "The Pomodoro Sprint";
        protocolDesc = "Cognitive stamina is lagging. Use white noise and eliminate all notification nodes. Start with 45-minute deep work blocks to build focus calluses.";
    }

    const report = {
      archetype, statusBg, protocol, protocolDesc,
      indices: {
        focus: Math.round(executionStrength * 10),
        resilience: Math.round((10 - anxietyLoad) * 10),
        vitality: Math.round((10 - fatigueIndex) * 10)
      },
      neuralStats: [
        { label: 'Calculative Stability', status: scores.sillyMistakes > 6 ? 'Critical' : 'Stable', color: scores.sillyMistakes > 6 ? 'text-rose-400' : 'text-emerald-400' },
        { label: 'Anxiety Buffer', status: highFear ? 'Low' : 'Resilient', color: highFear ? 'text-rose-400' : 'text-emerald-400' },
        { label: 'Reset Velocity', status: scores.recoverySpeed > 7 ? 'High' : 'Moderate', color: 'text-indigo-400' }
      ]
    };

    setAiAnalysis(report);
    
    const newEntry: PsychometricScore = {
      stress: Math.round(anxietyLoad),
      focus: Math.round(executionStrength),
      motivation: Math.round(scores.recoverySpeed),
      examFear: Math.round(scores.examStoicism),
      timestamp: new Date().toISOString().split('T')[0],
      studentSummary: `Current cognitive state: ${archetype}.`,
      parentAdvice: fatigueIndex > 6 ? " burnout risk. Rest suggested." : "Stable trajectory."
    };

    const newData = { ...data, psychometricHistory: [...(data.psychometricHistory || []), newEntry] };
    setData(newData);
    await api.saveEntity('Psychometric', { student_id: data.id, ...newEntry });

    setIsFinishing(false);
    setStep(questions.length);
  };

  const radarData = questions.map(q => ({
    subject: q.title,
    A: (scores[q.id] || 5) * 10,
    fullMark: 100
  }));

  if (step === questions.length && aiAnalysis) {
    return (
      <div className="max-w-6xl mx-auto space-y-12 animate-in zoom-in-95 duration-700 pb-32">
        {/* --- Archetype Header --- */}
        <div className="bg-white rounded-[4rem] border border-slate-200 shadow-2xl overflow-hidden">
             <div className={`p-12 md:p-20 text-white relative overflow-hidden ${aiAnalysis.statusBg}`}>
                <div className="absolute top-0 right-0 p-12 opacity-10 rotate-12"><Brain className="w-64 h-64" /></div>
                <div className="relative z-10 space-y-6">
                   <div className="inline-flex px-5 py-2 rounded-full bg-white/20 backdrop-blur-md text-[10px] font-black uppercase tracking-widest border border-white/20">Diagnostic Identification</div>
                   <h2 className="text-5xl md:text-8xl font-black italic tracking-tighter uppercase leading-none">{aiAnalysis.archetype}.</h2>
                   <p className="text-white/80 max-w-2xl text-xl font-medium leading-relaxed italic">"Your neurological preparation pattern has been mapped into the Solaris core."</p>
                </div>
             </div>

             {/* --- Strategic Review --- */}
             <div className="p-12 md:p-20 bg-slate-900 text-white space-y-16">
                <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-10">
                   <div className="space-y-4">
                      <h3 className="text-3xl font-black italic tracking-tighter uppercase text-indigo-400">Strategic Intelligence Review.</h3>
                      <p className="text-slate-400 font-medium italic">Actionable study protocols based on your performance pulse.</p>
                   </div>
                   <div className="h-48 w-48 shrink-0 bg-white/5 rounded-full flex items-center justify-center border border-white/10">
                      <ResponsiveContainer width="100%" height="100%">
                         <RadarChart cx="50%" cy="50%" outerRadius="80%" data={radarData}>
                            <PolarGrid stroke="#334155" />
                            <PolarAngleAxis dataKey="subject" tick={false} />
                            <RadarArea name="Balance" dataKey="A" stroke="#818cf8" fill="#818cf8" fillOpacity={0.5} />
                         </RadarChart>
                      </ResponsiveContainer>
                   </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
                   <div className="space-y-8">
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-12 bg-indigo-500/20 rounded-2xl flex items-center justify-center text-indigo-400 shadow-xl"><Target className="w-6 h-6" /></div>
                        <h4 className="text-xl font-black italic uppercase">Active Protocol</h4>
                      </div>
                      <div className="p-10 bg-white/5 border border-white/10 rounded-[3rem] space-y-4 hover:bg-white/[0.07] transition-colors">
                        <p className="text-indigo-300 text-2xl font-black italic tracking-tight">"{aiAnalysis.protocol}"</p>
                        <p className="text-sm text-slate-400 leading-relaxed font-medium italic">{aiAnalysis.protocolDesc}</p>
                      </div>
                   </div>

                   <div className="space-y-8">
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-12 bg-emerald-500/20 rounded-2xl flex items-center justify-center text-emerald-400 shadow-xl"><Lightbulb className="w-6 h-6" /></div>
                        <h4 className="text-xl font-black italic uppercase">Neural Optimization</h4>
                      </div>
                      <div className="space-y-4">
                        {aiAnalysis.neuralStats.map((item: any, i: number) => (
                          <div key={i} className="flex justify-between items-center p-6 bg-white/5 rounded-2xl border border-white/10 group hover:border-indigo-500/50 transition-all">
                             <span className="text-[10px] font-black uppercase text-slate-500 tracking-[0.3em] group-hover:text-slate-300">{item.label}</span>
                             <span className={`text-[10px] font-black uppercase tracking-widest ${item.color} px-4 py-1.5 rounded-full bg-white/5`}>{item.status}</span>
                          </div>
                        ))}
                      </div>
                   </div>
                </div>

                <div className="pt-10 border-t border-white/10 flex flex-col md:flex-row items-center justify-between gap-6">
                   <button onClick={() => setStep(0)} className="text-[11px] font-black uppercase tracking-[0.4em] text-slate-500 hover:text-indigo-400 transition-all flex items-center gap-3">
                      <RefreshCcw className="w-4 h-4" /> Re-Initialize Diagnostic Test
                   </button>
                   <button onClick={() => window.dispatchEvent(new CustomEvent('changeTab', { detail: 'dashboard' }))} className="bg-indigo-600 text-white px-10 py-4 rounded-2xl font-black text-xs uppercase tracking-widest shadow-2xl hover:bg-indigo-500 transition-all">Synchronize to Dashboard</button>
                </div>
             </div>
        </div>
      </div>
    );
  }

  const currentQ = questions[step];

  return (
    <div className="max-w-4xl mx-auto space-y-12 animate-in fade-in duration-500 pb-32 text-center">
      <div className="space-y-4 pt-10">
         <div className="inline-flex items-center gap-3 px-6 py-2 bg-indigo-50 border border-indigo-100 rounded-full text-[10px] font-black uppercase tracking-[0.4em] text-indigo-600 mx-auto">
            Dimension {step + 1} of {questions.length}
         </div>
         <h2 className="text-6xl font-black text-slate-900 tracking-tighter italic uppercase">Pulse Check.</h2>
         <p className="text-slate-400 font-medium italic">Answer honestly to calibrate your performance protocols.</p>
      </div>

      <div className="bg-white p-12 lg:p-20 rounded-[4rem] border border-slate-200 shadow-2xl space-y-12 relative overflow-hidden text-left group">
        <div className="absolute top-0 right-0 p-12 opacity-[0.03] group-hover:opacity-[0.08] transition-opacity"><Brain className="w-96 h-96" /></div>
        <div className="flex flex-col items-center text-center space-y-10 relative z-10">
          <div className="w-24 h-24 bg-indigo-50 text-indigo-600 rounded-[2.5rem] flex items-center justify-center shadow-inner border border-indigo-100">
            <currentQ.icon className="w-12 h-12" />
          </div>
          <div className="space-y-4">
            <h3 className="text-4xl font-black text-slate-900 tracking-tighter italic uppercase">{currentQ.title}</h3>
            <p className="text-slate-500 text-xl font-medium max-w-2xl italic leading-relaxed">"{currentQ.subtitle}"</p>
          </div>
          <div className="w-full max-w-xl pt-10 space-y-12">
            <input 
              type="range" min="1" max="10" step="1"
              value={scores[currentQ.id]}
              onChange={(e) => setScores({...scores, [currentQ.id]: parseInt(e.target.value)})}
              className="w-full h-4 bg-slate-100 rounded-full appearance-none cursor-pointer accent-indigo-600 shadow-inner"
            />
            <div className="flex justify-between mt-6">
               <div className="text-left"><div className="text-[8px] font-black text-slate-300 uppercase tracking-widest">MIN</div><div className="text-[10px] font-black text-slate-400 uppercase">{currentQ.low}</div></div>
               <div className="text-8xl font-black text-indigo-600 tracking-tighter tabular-nums leading-none">{scores[currentQ.id]}</div>
               <div className="text-right"><div className="text-[8px] font-black text-slate-300 uppercase tracking-widest">MAX</div><div className="text-[10px] font-black text-slate-400 uppercase">{currentQ.high}</div></div>
            </div>
            <div className="flex justify-between items-center gap-6 pt-12">
              <button disabled={step === 0} onClick={() => setStep(step - 1)} className="flex-1 py-5 bg-slate-50 text-slate-400 font-black rounded-2xl transition-all uppercase text-[10px] tracking-widest disabled:opacity-20">Back</button>
              <button onClick={() => step === questions.length - 1 ? handleFinish() : setStep(step + 1)} disabled={isFinishing} className="flex-[2] bg-indigo-600 text-white py-5 rounded-[2rem] font-black text-[10px] uppercase tracking-[0.3em] shadow-xl hover:bg-indigo-700 transition-all flex items-center justify-center gap-4">
                {isFinishing ? <Loader2 className="w-5 h-5 animate-spin" /> : step === questions.length - 1 ? 'Analyze Mindset' : 'Next Protocol'}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PsychometricTest;
